export type Vegetable = {
  id: string;
  name: string;
  tamilName: string; // Added for Tamil support
  image: string;
  price: number;
  origin: string;
  selected?: boolean;
};

export const SOUTHERN_VEGETABLES: Vegetable[] = [
  {
    id: "1",
    name: "Green Chilli",
    tamilName: "பச்சை மிளகாய்",
    image: "local://Chilli.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "2",
    name: "Tomato",
    tamilName: "தக்காளி",
    image: "local://Tomato.png",
    price: 30,
    origin: "Southern States",
  },
  {
    id: "3",
    name: "Onion",
    tamilName: "வெங்காயம்",
    image: "local://Onion.png",
    price: 45,
    origin: "Southern States",
  },
  {
    id: "4",
    name: "Potato",
    tamilName: "உருளை",
    image: "local://Potato.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "5",
    name: "Carrot",
    tamilName: "கேரட்",
    image: "local://Carrot.png",
    price: 60,
    origin: "Southern States",
  },
  {
    id: "6",
    name: "Green Beans",
    tamilName: "பீன்ஸ்",
    image: "local://Beans.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "7",
    name: "Broad Beans",
    tamilName: "அவரை",
    image: "local://Beans.png", // Using Beans.png as fallback
    price: 55,
    origin: "Southern States",
  },
  {
    id: "8",
    name: "Radish",
    tamilName: "முள்ளங்கி",
    image: "local://Raddish.png",
    price: 30,
    origin: "Southern States",
  },
  {
    id: "9",
    name: "Ginger",
    tamilName: "இஞ்சி",
    image: "local://Ginger.png",
    price: 120,
    origin: "Southern States",
  },
  {
    id: "10",
    name: "Brinjal (Eggplant)",
    tamilName: "கத்திரிக்காய்",
    image: "local://Brinjal.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "11",
    name: "Drumstick (Moringa)",
    tamilName: "முருங்கைக்காய்",
    image: "local://Drumstick.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "12",
    name: "Raw Mango",
    tamilName: "மாங்காய்",
    image: "local://RawMango.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "13",
    name: "Cabbage",
    tamilName: "கோஸ்",
    image: "local://Cabbage.png",
    price: 30,
    origin: "Southern States",
  },
  {
    id: "14",
    name: "Cauliflower",
    tamilName: "காலிப்ளவர்",
    image: "local://Cauliflower.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "15",
    name: "Bottle Gourd",
    tamilName: "சொரைக்காய்",
    image: "local://BottleGourd.png",
    price: 35,
    origin: "Southern States",
  },
  {
    id: "16",
    name: "Snake Gourd",
    tamilName: "புடலங்காய்",
    image: "local://Snake Gourd.png",
    price: 35,
    origin: "Southern States",
  },
  {
    id: "17",
    name: "Elephant Foot Yam",
    tamilName: "கருணை கிழங்கு",
    image: "local://Elephant.png",
    price: 60,
    origin: "Southern States",
  },
  {
    id: "18",
    name: "Taro Root",
    tamilName: "பிடிக்கருணை",
    image: "local://Taro Root.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "19",
    name: "Colocasia",
    tamilName: "சேப்பங்கிழங்கு",
    image: "local://Taro Root.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "20",
    name: "Lady's Finger (Okra)",
    tamilName: "வெண்டைக்காய்",
    image: "local://Lady's Finger.png",
    price: 35,
    origin: "Southern States",
  },
];
